### ISSUE TITLE
Matic initialization fail - TypeError: Matic is not a constructor

### ISSUE THREAD

**Issue by n1c01a5** [maticnetwork/matic.js#130]
When I try to instantiate Matic, I have this error:

TypeError: Matic is not a constructor

Here is the code:

import Matic from '@maticnetwork/maticjs'

// for mumbai testnet
const matic = new Matic({
	network: "testnet",
	version: "mumbai",
	parentProvider,
	maticProvider
  })

 matic.initialize()

Do you know why I have this error?

For information, I use node v14.

**Comment by n1c01a5** [comment]
import { createRequire } from 'module'
const require = createRequire(import.meta.url)

// import MaticPOSClient from '@maticnetwork/maticjs'
import pkg from '@maticnetwork/maticjs'

const { MaticPOSClient } = pkg

// and don't use initialize() function

**Comment by itzmeanjan** [comment]
> When I try to instantiate Matic, I have this error:
> 
> TypeError: Matic is not a constructor
> 
> Here is the code:
> 
> import Matic from '@maticnetwork/maticjs'
> 
> // for mumbai testnet
> const matic = new Matic({
> network: "testnet",
> version: "mumbai",
> parentProvider,
> maticProvider
> })
> 
> matic.initialize()
> 
> Do you know why I have this error?
> 
> For information, I use node v14.

Use it 👇 way 

```js
const Matic = require("@maticnetwork/maticjs").default;
```

**Comment by n1c01a5** [comment]
> > When I try to instantiate Matic, I have this error:
> > TypeError: Matic is not a constructor
> > Here is the code:
> > import Matic from '@maticnetwork/maticjs'
> > // for mumbai testnet
> > const matic = new Matic({
> > network: "testnet",
> > version: "mumbai",
> > parentProvider,
> > maticProvider
> > })
> > matic.initialize()
> > Do you know why I have this error?
> > For information, I use node v14.
> 
> Use it 👇 way
> 
> ```js
> const Matic = require("@maticnetwork/maticjs").default;
> ```

not working with node v14

**Comment by Qumeric** [comment]
I have the same issue.

**Comment by alexburciu** [comment]
try "POSClient"

**Comment by Shivam-Vatshayan** [comment]
const matic = require("@maticnetwork/maticjs").default;

const matic = new Matic({
      ^

SyntaxError: Identifier 'matic' has already been declared

Same issues still. 

Any solutions ?

**Comment by ujjwalgupta94** [comment]
@Shivam-Vatshayan its javascript simple error, you are using `matic` variable to top but seems like you wanted to use `Matic`.

**Comment by ujjwalgupta94** [comment]
Guys if anyone have any issue still, Please create a repo and share it here, so that others can help. 

Thanks

**Comment by ujjwalgupta94** [comment]
hey guys 

Also please follow this docs - 

https://docs.polygon.technology/docs/develop/ethereum-polygon/matic-js/get-started/

the code to create client should be this way - 

```
import { POSClient,use } from "@maticnetwork/maticjs"
import { Web3ClientPlugin } from '@maticnetwork/maticjs-web3'
import HDWalletProvider from "@truffle/hdwallet-provider"

// install web3 plugin
use(Web3ClientPlugin);

const posClient = new POSClient();
await posClient.init({
    network: 'testnet',
    version: 'mumbai',
    parent: {
      provider: new HDWalletProvider(privateKey, mainRPC),
      defaultConfig: {
        from : fromAddress
      }
    },
    child: {
      provider: new HDWalletProvider(privateKey, childRPC),
      defaultConfig: {
        from : fromAddress
      }
    }
});
```

there is no default export in latest version.

**Comment by ujjwalgupta94** [comment]
also we have examples code, you can have a look here - 

https://github.com/maticnetwork/matic.js/tree/master/examples

you can execute the simplest one i.e getting balance and understands the flow - 

https://github.com/maticnetwork/matic.js/blob/master/examples/pos/erc20/balance.js

**Comment by Vatshayan** [comment]
Hi Team, 
we are trying to send eth to Pol (vice versa) from plasma bridge.
we have used same apprcoh for connection to client. 

but transcation is not happening successfully. (we are not getting ETH/MATIC to our address)

deposit 
async function execute() {
  const plasmaClient = await getPlasmaClient();
  const erc20Token = plasmaClient.erc20(token, true);
  const result = await erc20Token.deposit(
    amount,
    process.env.USER1_FROM ,
    {
      maxPriorityFeePerGas: 10000000,
      gasPrice: 10000000,
    }
  );
  console.log("result=", result);
  const receipt = await result.getReceipt();
  console.log(receipt);
}
execute()


AND 

approve : 

const amount = "10000000000000000"; // amount in wei
const erc20TokenOnParent = plasma.parent.erc20;

async function execute() {
  const plasmaClient = await getPlasmaClient();
  const erc20Token = plasmaClient.erc20(erc20TokenOnParent, true);
  const result = await erc20Token.approve(amount);
  console.log(result);
  const receipt = await result.getReceipt();
  console.log(receipt);
}
execute()


Please check what should be done to get transcation successfully. 
Pls help
