### ISSUE TITLE
has no exported member 'TransactionReceipt'

### ISSUE THREAD

**Issue by ghost** [maticnetwork/matic.js#132]
When I tried to connect to the MaticPOSClient with Angular 9.1.3 a got error
<img width="1025" alt="Screen Shot 2020-12-12 at 7 11 36 PM" src="https://user-images.githubusercontent.com/31731894/101990176-045b4b00-3cae-11eb-918f-b3495885bcde.png">
Angular v9.1.3
web3 v1.3.0
matic.js v2.0.15

**Comment by itzmeanjan** [comment]
This does look like an error in `web3/types` package.

**Comment by VoroshilovMax** [comment]
Can I resolve it myself or it will be resolve in the next update in the Matic.js package?

**Comment by itzmeanjan** [comment]
It's a different package, not associated with matic.js, as I see. Tell me more about what you're trying to attain.

**Comment by jdkanani** [comment]
@itzmeanjan Do you think it's problem with the web3 version matic.js uses?

**Comment by VoroshilovMax** [comment]
This problem appears after MaticPOSClient initialization. Code example:
```
import { MaticPOSClient } from '@maticnetwork/maticjs'
...
  connectToMatic() {
    return new MaticPOSClient({
      network: "testnet",
      version: "mumbai",
      parentProvider: window.web3.currentProvider,
      maticProvider: new Web3("https://rpc-mumbai.matic.today"),
      posRootChainManager: "0xBbD7cBFA79faee899Eaf900F13C9065bF03B1A74",
      posERC20Predicate: "0xdD6596F2029e6233DEFfaCa316e6A95217d4Dc34"
    });
  }

  async burn() {
    if (this.numberOfTokens > 0) {
      let maticPOSClient = this.connectToMatic();
      let childToken = '0x53D06C06B5A9532edd2E18AC454a0E3fC9824a0e'; 
      let web3 = new Web3()
      let amount = web3.utils.toWei(String(this.numberOfTokens), "ether")
      let from = this.userWallet
      let transaction = await maticPOSClient.burnERC20(childToken, amount, { from });
      console.log(transaction);
    } else {
      console.log("Value must be bigger that 0")
    } 
  }
```
@itzmeanjan

**Comment by itzmeanjan** [comment]
This [dependency](https://github.com/maticnetwork/matic.js/blob/a3cc75fe02641361a51da734475c772e6249b982/package.json#L48) in matic.js is not required anymore. 

And it has been [deprecated](https://www.npmjs.com/package/@types/web3), we can rely on web3.js itself from now.

**Comment by itzmeanjan** [comment]
> This problem appears after MaticPOSClient initialization. Code example:
> 
> ```
> import { MaticPOSClient } from '@maticnetwork/maticjs'
> ...
>   connectToMatic() {
>     return new MaticPOSClient({
>       network: "testnet",
>       version: "mumbai",
>       parentProvider: window.web3.currentProvider,
>       maticProvider: new Web3("https://rpc-mumbai.matic.today"),
>       posRootChainManager: "0xBbD7cBFA79faee899Eaf900F13C9065bF03B1A74",
>       posERC20Predicate: "0xdD6596F2029e6233DEFfaCa316e6A95217d4Dc34"
>     });
>   }
> 
>   async burn() {
>     if (this.numberOfTokens > 0) {
>       let maticPOSClient = this.connectToMatic();
>       let childToken = '0x53D06C06B5A9532edd2E18AC454a0E3fC9824a0e'; 
>       let web3 = new Web3()
>       let amount = web3.utils.toWei(String(this.numberOfTokens), "ether")
>       let from = this.userWallet
>       let transaction = await maticPOSClient.burnERC20(childToken, amount, { from });
>       console.log(transaction);
>     } else {
>       console.log("Value must be bigger that 0")
>     } 
>   }
> ```
> 
> @itzmeanjan

I couldn't reproduce this on my machine. So it fails after `let maticPOSClient = this.connectToMatic();` line, is it ?

@VoroshilovMax

**Comment by VoroshilovMax** [comment]
> > This problem appears after MaticPOSClient initialization. Code example:
> > ```
> > import { MaticPOSClient } from '@maticnetwork/maticjs'
> > ...
> >   connectToMatic() {
> >     return new MaticPOSClient({
> >       network: "testnet",
> >       version: "mumbai",
> >       parentProvider: window.web3.currentProvider,
> >       maticProvider: new Web3("https://rpc-mumbai.matic.today"),
> >       posRootChainManager: "0xBbD7cBFA79faee899Eaf900F13C9065bF03B1A74",
> >       posERC20Predicate: "0xdD6596F2029e6233DEFfaCa316e6A95217d4Dc34"
> >     });
> >   }
> > 
> >   async burn() {
> >     if (this.numberOfTokens > 0) {
> >       let maticPOSClient = this.connectToMatic();
> >       let childToken = '0x53D06C06B5A9532edd2E18AC454a0E3fC9824a0e'; 
> >       let web3 = new Web3()
> >       let amount = web3.utils.toWei(String(this.numberOfTokens), "ether")
> >       let from = this.userWallet
> >       let transaction = await maticPOSClient.burnERC20(childToken, amount, { from });
> >       console.log(transaction);
> >     } else {
> >       console.log("Value must be bigger that 0")
> >     } 
> >   }
> > ```
> > 
> > 
> > @itzmeanjan
> 
> I couldn't reproduce this on my machine. So it fails after `let maticPOSClient = this.connectToMatic();` line, is it ?
> 
> @VoroshilovMax

I found that this bug appears only if you work in .ts file. If switch all logic to the .js file everything will work fine. I think this obvious.

**Comment by itzmeanjan** [comment]
> I found that this bug appears only if you work in .ts file. If switch all logic to the .js file everything will work fine. I think this obvious.

If that's possible for you, it's fine.

But @jdkanani I think we can consider removing [`@types/web3`](https://github.com/maticnetwork/matic.js/blob/a3cc75fe02641361a51da734475c772e6249b982/package.json#L48) from dependency & start relying on web3's own type system for TypeScript part.

**Comment by jdkanani** [comment]
I have created issue #135 for the same. Have to debug more.
