### ISSUE TITLE
Cleanup code, use modular architecture and use import needed functions for better tree shaking

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/matic.js#135]
- [x] Add publish script https://github.com/maticnetwork/matic.js/pull/142
- [x] Remove dist folder from git history https://github.com/maticnetwork/matic.js/pull/140
- [x] Use Github CI actions https://github.com/maticnetwork/matic.js/pull/137 
- [x] Remove unwanted files like `test-blockchain` https://github.com/maticnetwork/matic.js/pull/136 
- [x] Add eslint camelcase rule https://github.com/maticnetwork/matic.js/pull/144

**Comment by cruzdanilo** [comment]
as a workaround for bundle size optimization, i did the following:

import from lib:
```js
import { MaticPOSClient } from '@maticnetwork/maticjs/lib'
```

webpack config:
```js
const { ContextReplacementPlugin } = require('webpack')
const ContextElementDependency = require('webpack/lib/dependencies/ContextElementDependency')
return {
  plugins: [
    new ContextReplacementPlugin(/@maticnetwork\/meta\/network$/, (context) => {
      Object.assign(context, {
        resolveDependencies: (_, __, callback) => {
          callback(
            null,
            [
              ['./mainnet/v1/index.json'],
              ['./testnet/mumbai/index.json'],
              ...[
                'plasma/ChildERC20',
                'plasma/RootChain',
                'pos/RootChainManager',
                'pos/RootTunnel',
              ].map((contract) => [
                `./mainnet/v1/artifacts/${contract}.json`,
                `./testnet/mumbai/artifacts/${contract}.json`,
              ]),
            ].map(([request, userRequest]) => new ContextElementDependency(request, userRequest)),
          )
        },
      })
    }),
  ],
}
```

**Comment by ujjwalgupta94** [comment]
We have added all of the above task in v3. Now size of the min bundle is around - 150kb. We have also added plugin support using which various others small codes can be shipped seperately.
