### ISSUE TITLE
Update CDN version in README

### ISSUE THREAD

**Issue by VogtAI** [maticnetwork/matic.js#145]
I was stuck for over an hour using the CDN version 2.0.1 which is shown in the README trying to call the function depositEtherForUser(...)

`ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'network' of undefined
TypeError: Cannot read property 'network' of undefined `

Using the latest version worked like a charm:

`<script src="https://cdn.jsdelivr.net/npm/@maticnetwork/maticjs@latest/dist/matic.js"></script>`

**Comment by jdkanani** [comment]
@VogtAI Thanks for the report. That shouldn't happen since `jsdelivr@latest` should give the latest version. I will check and fix.

**Comment by jdkanani** [comment]
Fixed on master branch.
