### ISSUE TITLE
Add receiveMessage method for tunnel contract

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/matic.js#152]
Tunnel contract helps developers to move arbitrary data from Ethereum to Matic and Matic to Ethereum. 

While moving data from Matic to Ethereum, one event is generated `event MessageSent(bytes message)` - https://github.com/maticnetwork/pos-portal/blob/master/contracts/tunnel/BaseChildTunnel.sol#L13

There is one method on RootTunnel, `receiveMessage`, that needs to be called on the Ethereum chain to get the `data`.  After the checkpoint, the user will send one tx (function `receiveMessage` at `RootTunnel` contract) on the Ethereum chain. That tx will validate the event/log and processes the received `data` based on the DApp developer's custom logic. DApp developer will write custom logic here: https://github.com/maticnetwork/pos-portal/blob/master/contracts/tunnel/BaseRootTunnel.sol#L217

To generate the payload for `receiveMessage` and to call that function, we need one more method on Matic.js. Here is the pseudocode for it:

```js
const contractAddress = rootTunnelContractAddressOnEthereum
const txHash = txHashWhichHasMessageSentEventOnMatic
const logSignature = keccak256('MessageSent(bytes)')
export function processReceivedMessage(contractAddress, txHash) {
    const payload = await this.exitManager.buildPayloadForExitHermoine(txHash, logSignature)
    return rootTunnelContract.at(contractAddress).methods.receiveMessage(payload)
}
```

**Comment by itzmeanjan** [comment]
`receiveMessage(bytes data...)` in ChildTunnelImplementation, right ?

**Comment by jdkanani** [comment]
While at it, we can also expose `buildPayload` for custom data to developers. They can use it internally if their custom logic forces `receiveMessage(bytes data)` to be called from another function/contract and not directly.
