### ISSUE TITLE
3000 post requests to RPC for function call maticPOSClient.exitERC20??

### ISSUE THREAD

**Issue by VogtAI** [maticnetwork/matic.js#153]
Hey there,

when executing maticPOSClient.exitERC20(burnHash, {encodeAbi:true, legacyProof:true, from:user})
Chrome does 3000 post requests to the RPC within around 10 seconds. The function works fine otherwise, I'm just wondering if this is intended since it appears to be unnecessary load to the RPC.

**Comment by itzmeanjan** [comment]
Yes this is required.

Due to the fact, during legacy proof generation, it needs to make RPC queries for fetching block number, hash, txRootHash, ReceiptHash for lots of blocks, which will be eventually fed into `exit` function i.e. for performing POS exit.

**Comment by jdkanani** [comment]
@VogtAI We are optimizing non-legacy api. Once it's done, you don't have to use `legacyProof` on UI.

**Comment by Jay54520** [comment]
How to lower the request speed as RPC provider has a rate limit of 100/second, so connection will be reset.
