### ISSUE TITLE
Unable to use exitERC721 function

### ISSUE THREAD

**Issue by adi44** [maticnetwork/matic.js#179]
Hey! I have been trying to use exiterc721 function. Whenever I run it, it throws an exception. they nft was minted on matic chain. After that I burnt it and executed exiterc721 function.

**Comment by rahuldamodar94** [comment]
What error do you face ?

**Comment by adi44** [comment]
Hey @rahuldamodar94 It has been resolved now.

**Comment by Josedpv** [comment]
Hey @adi44 can you please show me how did you solved the issue? I have been stuck there for a while
