### ISSUE TITLE
How to use ethers.js signer as web3 provider?

### ISSUE THREAD

**Issue by miguelmota** [maticnetwork/matic.js#188]
Hi, is ethers.js signer supported instead of web3.js provider? Thanks

**Comment by rahuldamodar94** [comment]
Not supported,

**Comment by sdelvalle57** [comment]
I believe this issue must be addressed, ethers is widely used, 
I think @rahuldamodar94 is providing a bad support by just answering that

**Comment by rahuldamodar94** [comment]
Hey @sdelvalle57 @miguelmota 

Sorry about that response. 
what I meant was that, it is not supported currently, but it is on the roadmap
Shall post here when its added.

**Comment by ujjwalgupta94** [comment]
Hey @sdelvalle57 @miguelmota , we have finished new version of maticjs which will support ethers and web3 both. It has lot of additional changes.

Right now its in beta version, we are working on testing and reviewing. It would be great if you guys can provide feedback and anything you want to be added.

Here is discussion link - https://github.com/maticnetwork/matic.js/discussions/282

**Comment by miguelmota** [comment]
Thanks @ujjwalgupta94! we'll check it out

**Comment by ujjwalgupta94** [comment]
we have released new version of maticjs with support for ethers, please read docs here - https://maticnetwork.github.io/matic.js/docs/setup/ethers/

**Comment by ujjwalgupta94** [comment]
we have also added examples for different cases, please have a look here - https://github.com/maticnetwork/maticjs-ethers/tree/main/examples
