### ISSUE TITLE
[Inquiry] Project status?

### ISSUE THREAD

**Issue by will-holley** [maticnetwork/matic.js#189]
Hello,

A few questions:

- Is this being actively developed? 
- Is there a roadmap?
- If either of the previous answers is no, why not?  Is this something that additional community involvement can help with?

Cheers,

Will

**Comment by SteversIO** [comment]
Definitely doesnt feel like it. their only partially useful readme references a file that doesnt exist.

**Comment by jdkanani** [comment]
We are pushing changes on master and releasing the new versions now and then. 

There are few things we need to change --  like using plasma-core lib for proof generation and optimize it. But currently, we are focusing on other things and come back with a roadmap on Matic.js

@ujjwalgupta94 will be leading the new roadmap.

**Comment by will-holley** [comment]
In lieu of a roadmap, is there an task tracking system that can be shared in order to invite collaboration and accelerate velocity?

**Comment by ujjwalgupta94** [comment]
Right now, we are using github issue to track issues and take feature request. You can help by replying to issues and sending PR. 

The plan is to use github discussion in future.

**Comment by ujjwalgupta94** [comment]
@will-holley we are now using github project for tracking task. Take a look here - https://github.com/maticnetwork/matic.js/projects/1

**Comment by ujjwalgupta94** [comment]
We have also added the roadmap in https://github.com/maticnetwork/matic.js/projects/1 . we will be actively updating the task here.

I hope this answer the all questions.
