### ISSUE TITLE
Problem with npm install !

### ISSUE THREAD

**Issue by fastepic** [maticnetwork/matic.js#194]
npm install @maticnetwork/maticjs@2.0.40
npm WARN deprecated ethereumjs-block@2.2.0: New package name format for new versions: @ethereumjs/block. Please update.
npm WARN deprecated ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Unexpected end of JSON input while parsing near '..."mime-types":"~2.0.11'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/robert/.npm/_logs/2021-05-06T16_46_44_187Z-debug.log

**Comment by ujjwalgupta94** [comment]
this is occuring due to deprecated package dependency. We will work on this.

**Comment by KirankumarAmbati** [comment]
`npm ERR! Unexpected end of JSON input while parsing near '..."mime-types":"~2.0.11'`

From my experience, this might be a general error with npm. It might be an issue with npm caching. 

Trying these steps might fix the issue:

1. `npm cache clear --force`
2. Delete `node_modules` and `package.lock.json`
3. Run `npm install`

**Comment by andrewkmin** [comment]
late followup here, but what's the current recommended version of node to be running with this? having some trouble getting the dev env set up locally.
