### ISSUE TITLE
Question: Withdraw NFT from Matic to Ethereum

### ISSUE THREAD

**Issue by blmalone** [maticnetwork/matic.js#199]
Hello, 

I'd like to understand the process of withdrawing ERC721 tokens that were minted on the Polygon Network. 

Can an ERC721 token be minted on the Polygon network then withdrawn to L1? Or do withdrawals only work if the ERC721 token is first minted on L1, transferred to L2 and _then_ withdrawn back to L1?

If the former is true, what needs to be deployed on L1 to make this work i.e. Another ERC721 contract that has some customizations? 

I see you've got some sample code for this, but it is not clear on how one would mint on Polygon and then later withdraw. 

References:
[1] - https://github.com/maticnetwork/matic.js/blob/80a482ea4931ebf9cf2906ca541cffb668c63e43/examples/node/initiate-withdraw-ERC721.js
[2] - https://github.com/maticnetwork/matic.js/blob/80a482ea4931ebf9cf2906ca541cffb668c63e43/examples/node/confirm-withdraw-ERC721.js

**Comment by anurag-arjun** [comment]
This should help: https://docs.matic.network/docs/develop/ethereum-matic/pos/mintable-assets

**Comment by anurag-arjun** [comment]
Please feel free to open if you have any doubts.

**Comment by kr-pratikp** [comment]
@anurag-arjun
After referring to the document on POS MATIC bridge, I understood that 
1) Transferring ERC-721 from ETH to MATIC is a deposit
2) Transferring ERC-721 from MATIC to ETH is withdraw

If the ERC-721 token is created on MATIC and if it is required to transfer to the Ethereum network, then what could be the process? (Basically, only withdrawal)
As per the documentation, the token will be burned on MATIC and unlocked on Ethereum, but in this case, the token is not there on the Ethereum network to be unlocked. 

@blmalone Have you got any solution on this?

**Comment by rahuldamodar94** [comment]
@kr-pratikp 

Please refer to https://wiki.polygon.technology/docs/develop/ethereum-polygon/mintable-assets 
You can use matic.js for bridging - https://wiki.polygon.technology/docs/develop/ethereum-polygon/matic-js/get-started

**Comment by kr-pratikp** [comment]
@rahuldamodar94 README file stats the steps to deploy the pos contracts on localhost and mainnet. If we want to deploy the smart contracts on a matic Mumbai network, then which steps need to be followed?

**Comment by kr-pratikp** [comment]
@rahuldamodar94 When I tried to call function 'withdrawStartWithMetaData' for ERC-721, I am getting error like: err { code: -32000, message: 'execution reverted' }. I can burn the token on the child chain using the 'withdrawStart' function, but I want some metadata to be transferred on the root chain, so I used 'withdrawStartWithMetaData', but got an error.
Can you please help me with this issue?
