### ISSUE TITLE
Version 1.0.0-beta.1

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/matic.js#2]
For version v1.0.0-beta.1, following checklist should be required:

- [x] Deposit
- [x] Local withdraw
- [x] Withdraw with backend APIs
- [x] Tx/receipt/header proof and verify proof APIs
- [x] Webpack setup
- [x] Eslint fixes for future pull requests
- [x] Necessary testcases
- [x] Documentation

**Comment by jdkanani** [comment]
@shahbhavir Eslint fixes for future pull requests?

**Comment by shahbhavir** [comment]
> @shahbhavir Eslint fixes for future pull requests?

implemented here: https://github.com/maticnetwork/matic.js/pull/1

**Comment by shahbhavir** [comment]
@saylip @0xAshish let's push some example code

**Comment by shahbhavir** [comment]
Published package `maticjs` with `next` tag. Can be installed with `npm install --save maticjs@next`

**Comment by shahbhavir** [comment]
Majority of the tasks are implemented here: https://github.com/maticnetwork/matic.js/pull/1
Package renaming, publishing, and other changes are here: https://github.com/maticnetwork/matic.js/pull/7
