### ISSUE TITLE
maticPOSClient.depositSingleERC1155ForUser is timing out.

### ISSUE THREAD

**Issue by SteversIO** [maticnetwork/matic.js#200]
WIth a properly configured maticPOSClient i attempt to invoke depositSinglERC1155ForUser and it hangs until the default timeout of 750 seconds is reached.

I know the client is properly configured because i can use it to call the `.balanceOfERC721` and `.balanceOfERC20` functinos successfully.

Here's the code that fails:
```
const singleDepositTx = maticPOSClient.depositSingleERC1155ForUser(
        megaTokensContract.address,
        from,
        tokenId,
        amountToTransfer,
        [],
        {
            from,
            gasPrice: '200000000000'
        }
    );
```

Worth noting, my code below WORKS and successfully sends tokens across the PoS bridge:
```
let user = '0xd954F4513BdE1E00F3986630A7e73c4f9aA564fE'; 
    let rootToken = '0x4b048C00d746bd2559FcA9f9733D2A6a2a8ef3D9'; 
    let tokenIds = ['1']; 
    let amounts = [5]; 
    let data = [];
    let depositData = web3.eth.abi.encodeParameters(['uint256[]', 'uint256[]', 'bytes'], [tokenIds, amounts, data]);

    // (2) get contract
    let artifact = require("./pos-portal/artifacts/RootChainManager.json"); 
    const proxyForRootChainManagerAddress = '0xBbD7cBFA79faee899Eaf900F13C9065bF03B1A74'; 
    let root = new web3.eth.Contract(artifact.abi, proxyForRootChainManagerAddress);

    // (3) call depositFor
    let gasPrice = '20000000000';
    let tx = root.methods.depositFor(user, rootToken, depositData).send({from: accounts[0], gasPrice });
```

**Comment by rahuldamodar94** [comment]
@SteversIO Are your trying to move your asset from Goerli <> Mumbai ? 
If yes, then you might want to give a higher gas price and gas limit on goerli. There seems to be some issue in Goerli recently.

**Comment by SteversIO** [comment]
Hey Rahul,

I've already set higher gas prices in my calls.  That is how I am able to get the deposit working when I manually invoke it with the code I wrote out.

I'm saying that if I use the Matic JS client and the helper function it exposes with . depositSingleERC1155ForUser then it hangs.

**Comment by fuzious** [comment]
@SteversIO Sorry for the delayed response, i just tried it on my end and it seems to work fine at my end currently. Here is my script
`
const tx = await maticPOSClient.depositSingleERC1155ForUser(
      configPos.root.DERC1155,
      configPos.user.address,
      '123',
      '1',
      '',
      {
        from: configPos.user.address,
        gasPrice: '900000000000',
        gas: '550000',
      }
    )
`
Here is the transaction : https://goerli.etherscan.io/tx/0xa36c5785022f61efb38c87567cd46764aaa93d4efc34866669232474ed6560d7
