### ISSUE TITLE
isSingleERC1155ExitProcessed throws "TypeError: i is null" for old TXs

### ISSUE THREAD

**Issue by KirienzoEth** [maticnetwork/matic.js#204]
Hi !
Since last week, ERC1155 tokens that were waiting to be retrieved on L1 after being burned on L2 are throwing an error when checked for exit being processed:
`maticPOSClient.isSingleERC1155ExitProcessed("0xbfc70c164f6951d9c9f3f87f2d1361ff216eb3d6fe9571430bd3f0711847a782");`
This check throws the error "TypeError: i is null" in the file "matic.umd.js", and when I try to call `exitSingleERC1155` on it I get the same error. Batch operations are also failing.

Note that everything was working fine beginning of last week, and it doesn't affect all withdrawals.

Can someone help me on this ?

Here is an example you can play with:
```
<html >
  <meta charset="UTF-8">
  <body>
    <script src="https://unpkg.com/@maticnetwork/maticjs@latest/dist/matic.js"></script>
    <script>
      const brokenTransactions = [
        '0xbfc70c164f6951d9c9f3f87f2d1361ff216eb3d6fe9571430bd3f0711847a782',
        '0x2550f010066187641f688df808ebe4abd730f6c8a2a28f1a5d01e10c6d99d8e7',
      ];

      const maticPOSClient = new Matic.MaticPOSClient({
        network: 'mainnet',
        version: 'v1',
        parentProvider: 'eth-mainnet-rpc',
        maticProvider: 'matic-rpc'
      });

      brokenTransactions.forEach((transactionHash) => {
        document.body.innerHTML += `<div id="${transactionHash}">TX ${transactionHash}, status: <span class="status">Pending</span></div>`
        maticPOSClient.isSingleERC1155ExitProcessed(transactionHash)
          .then(response => {
            console.log(`for ${transactionHash}`, response);
            document.getElementById(transactionHash).getElementsByClassName('status')[0].innerHTML = 'Success';
          })
          .catch(e => {
            console.error(`for ${transactionHash}`, e);
            document.getElementById(transactionHash).getElementsByClassName('status')[0].innerHTML = 'Error, check console';
          });
      })
    </script>
  </body>
</html>
```

**Comment by KirienzoEth** [comment]
Hey @rahuldamodar94 ! Thanks for taking this issue :)
Do you have any news on this ? It's been a week and we still can't complete withdrawals :/
Do you have any indication on how we could enable this temporarily without using the SDK ? (if the error comes from there)

**Comment by fuzious** [comment]
Hi @KirienzoEth , sorry for the delayed response,
Actually I was able to produce it on my end, and I am getting `false` for this transaction hash. You might want to check that your pos client is properly configured. Here's how I did it: 
```
return new MaticPOSClient({
    network: "mainnet", // For mainnet change this to mainnet
    version: "v1", // For mainnet change this to v1
    parentProvider: new HDWalletProvider(
      config.user.privateKey,
      config.root.RPC
    ),
    maticProvider: new HDWalletProvider(
      config.user.privateKey,
      config.child.RPC
    ),
    // parentDefaultOptions: { from: config.user.address }, // optional, can also be sent as last param while sending tx
    // maticDefaultOptions: { from: config.user.address }, // optional, can also be sent as last param while sending tx
  });
```

**Comment by KirienzoEth** [comment]
Hey @fuzious , thanks for your answer.
Can you try using RPC URLs instead ? I'm following the doc the letter by instantiating my SDK like this:
```
const maticPOSClient = new MaticPOSClient({
  network: 'mainnet',
  version: 'v1',
  parentProvider: 'https://mainnet.infura.io/v3/my-key',
  maticProvider: 'https://rpc-mainnet.maticvigil.com/v1/my-key'
});
```
But I'm still getting the error :/

**Comment by ujjwalgupta94** [comment]
ohk, public RPC can have issue sometimes due to load or threshold limit. You can find list of RPC to be used from here- https://docs.matic.network/docs/develop/network-details/network/

Anyway i am glad, you were able to solve the issue.

**Comment by KirienzoEth** [comment]
Thanks ! It was actually a private one so, weird xD
