### ISSUE TITLE
maticPOSClient.exitERC20 returns error

### ISSUE THREAD

**Issue by alexandrewolff** [maticnetwork/matic.js#205]
When I run maticPOSClient.exitERC20 (with correct burnTxHash value) it always returns the following error:

TypeError: Cannot read property 'blockNumber' of null

Even after waiting a long time to make sure checkpoint have been validated.

**Comment by fuzious** [comment]
@alexandrewolff Are you still facing this issue?

**Comment by ujjwalgupta94** [comment]
@fuzious let's handle the error and show a user friendly message.

**Comment by alexandrewolff** [comment]
No the error was on my side, my MaticPOSClient providers were not well configured. Indeed a clearer error message would have helped 🙂

**Comment by ujjwalgupta94** [comment]
Opening this to add clear user message.

**Comment by ujjwalgupta94** [comment]
we debugged more and found - error is coming from web3.js directly, so can't do anything here. If you see we can improve  anything let us know.
