### ISSUE TITLE
MetaMask - RPC Error: MetaMask Tx Signature: User denied transaction signature.

### ISSUE THREAD

**Issue by lopeselio** [maticnetwork/matic.js#206]
Our game works flawlessly on the rinkeby testnetwork. We have deployed our contracts to mumbai tesnet successfully. But when we make a transaction, we are stuck on this issue. 
1. MetaMask - RPC Error: MetaMask Tx Signature: User denied transaction signature.
2. Uncaught (in promise) Error: Transaction has been reverted by the EVM:
We are building dungeon crawler on the matic mumbai tesnet. It is an RPG game that has NFTs and a DAO in the game with our very own ERC-20 token $DGN

**Comment by lopeselio** [comment]
![image](https://user-images.githubusercontent.com/43913734/120124393-fc4a8580-c1d1-11eb-900e-6c237abdd624.png)

Shows a high gas limit and gas price as well

**Comment by fuzious** [comment]
@lopeselio Can you please elaborate or provide the scripts, which are failing.

**Comment by lopeselio** [comment]
Hey @fuzious , we were building this project for 0x hack. https://github.com/de-Dungeon-Crawler/DungeonCrawler-Polygon/blob/main/blockchain/truffle-config.js   
I have discussed this issue with the mentors from Polygon as we need help on this one.

**Comment by lopeselio** [comment]
Our smart contracts are deployed to polygon mumbai testnet. The project works absolutely fine on Rinkeby. We are facing some issues with the Mumbai Testent. 

Thanks and cheers.

**Comment by fuzious** [comment]
Hey @lopeselio contacted you on 0x discord , we will carry this forward there.

**Comment by bboynton97** [comment]
Please don't do that because then no one else can learn from this issue
