### ISSUE TITLE
runnig the maticPOSClient.exitERC20 errer?

### ISSUE THREAD

**Issue by fenQY** [maticnetwork/matic.js#207]
mycode: 
const burnHash = '0x37991a88ab2b4602e9ff942f99144501749c4d8c21e2323f18f5f1b4d3ec607f'
maticPOSClient.exitERC20(burnHash, options).then((res)=>{
            console.log("res: ", res);
            process.exit(0)
}).catch((err)=>{
            console.log("err: ", err);
            process.exit(0)
        })

errers:
err:  AssertionError [ERR_ASSERTION]: Burn transaction has not been checkpointed as yet
    at t.<anonymous> (D:\Project\solidity\matic\eth\node_modules\@maticnetwork\maticjs\dist\matic.node.js:8:26981)
    at D:\Project\solidity\matic\eth\node_modules\@maticnetwork\maticjs\dist\matic.node.js:8:23381
    at Object.next (D:\Project\solidity\matic\eth\node_modules\@maticnetwork\maticjs\dist\matic.node.js:8:23486)
    at r (D:\Project\solidity\matic\eth\node_modules\@maticnetwork\maticjs\dist\matic.node.js:8:22200)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by fenQY** [comment]
More than 30 minutes since run maticPOSClient.burnERC20.

**Comment by fenQY** [comment]
More than 3h since run maticPOSClient.burnERC20, always this errer

**Comment by rahuldamodar94** [comment]
@fenQY 

you need to wait for the checkpoint before call the exitERC20 function. 
you can check if the checkpoint has happened or not using this public API 
https://apis.matic.network/api/v1/mumbai/block-included/3720704

You will have to pass the block number of your burn transaction on matic mainnet !

**Comment by fenQY** [comment]
thank you!   when I get the checkpoint info call the exitERC20 function was ok.
________________________________
发件人: Rahul Prabhu ***@***.***>
发送时间: 2021年6月1日 13:38
收件人: maticnetwork/matic.js ***@***.***>
抄送: zhangming ***@***.***>; Mention ***@***.***>
主题: Re: [maticnetwork/matic.js] runnig the maticPOSClient.exitERC20 errer? (#207)


@fenQY<https://github.com/fenQY>

you need to wait for the checkpoint before call the exitERC20 function.
you can check if the checkpoint has happened or not using this public API
https://apis.matic.network/api/v1/mumbai/block-included/3720704

You will have to pass the block number of your burn transaction on matic mainnet !

―

**Comment by fenQY** [comment]
How often does checkpoint commit?    I completed the above transaction yesterday.
