### ISSUE TITLE
TypeError: param is undefined

### ISSUE THREAD

**Issue by sdelvalle57** [maticnetwork/matic.js#213]
Im trying to bridge tokens from ethereum to matic but Ive been having this issue and cannot get to find the answer, I believe this issue comes from `ABICoder`

FYI Im using nextjs with typescript

````
const posClientParent = (account: string) => {
    const maticPoSClient = new MaticPOSClient({
        network: "testnet",
        version: "mumbai",
        maticProvider:  new Web3(`https://rpc-mumbai.maticvigil.com/v1/${process.env.MATIC_API_KEY}`),
        parentProvider: window.ethereum,
        parentDefaultOptions: { from: account },
        maticDefaultOptions: { from: account },
        posRootChainManager: '0xBbD7cBFA79faee899Eaf900F13C9065bF03B1A74',
        posERC20Predicate: '0xdD6596F2029e6233DEFfaCa316e6A95217d4Dc34', 
    });
    return maticPoSClient;
  };

await posClientParent.approveERC20ForDeposit("0xBBA4d2917790B35822F37237f7963C261A8399a9", amount, { from });

````
Respone: 

![image](https://user-images.githubusercontent.com/12821552/121417497-97103600-c92f-11eb-86c8-fe6f3576e85c.png)

**Comment by ujjwalgupta94** [comment]
issue is coming from web3.js but not sure why ? Could you check your value once @sdelvalle57 - amount, from , account etc ?

**Comment by sdelvalle57** [comment]
Solved, I was sending `BigNumberish` from `ethersjs` as amount. Changed it to string and it worked

**Comment by ujjwalgupta94** [comment]
Good 👍
