### ISSUE TITLE
Setup test framework

### ISSUE THREAD

**Issue by shahbhavir** [maticnetwork/matic.js#22]
[Mocha](https://github.com/mochajs/mocha) or something similar

**Comment by ujjwalgupta94** [comment]
Matic.js is meant to be interacting with polygon bridge, so i am not sure if this can be suited for generic contract test. For having an idea about test cases or how to test setup, please have a look at test codes inside test folder. 

If you have something else in mind like any part of matic.js which we can expose and users can benefit from it, feel free to let us know.

On the other hand - You should use web3.js or ether.js for generic contract call/testing.
