### ISSUE TITLE
How can i deploy a token on matic that store some amount of matic in contact during buy/sell.

### ISSUE THREAD

**Issue by fawazraz** [maticnetwork/matic.js#222]

**Comment by fuzious** [comment]
Hi @fawazraz ,
If you want to just deploy a token on matic you can follow this guide:  https://docs.matic.network/docs/develop/remix for deployment. Can you please elaborate your use case some more, so that I can understand your problem.

**Comment by fawazraz** [comment]
during contract execution,need to store some % of matic fee in dev wallet.you can contact me through telegram (@fawaz_raz).for paid partnership

**Comment by fuzious** [comment]
@fawazraz , if I am geeting you right, you can request some development tokens from the matic faucet here https://faucet.matic.network/

**Comment by fawazraz** [comment]
iam not a developer.if you can help me to create this token and a dapp.it would be great.please contact me on telegram
