### ISSUE TITLE
AssertionError: Burn transaction has not been checkpointed as yet

### ISSUE THREAD

**Issue by sdelvalle57** [maticnetwork/matic.js#223]
Im getting this error using mumbai network. Havent tried on mainnet yet.

````
const txHash = "0xdba139794982873b00827003be64db0ec0205886f7450fa773af747009bf91b1";
const isProcessed = await maticPOSClient.isERC20ExitProcessed(txHash);
````

What would be the best workaround to check for a txHash?

**Comment by ujjwalgupta94** [comment]
You can check here - https://explorer-mumbai.maticvigil.com/tx/0xdba139794982873b00827003be64db0ec0205886f7450fa773af747009bf91b1/token-transfers

**Comment by fuzious** [comment]
Hi, @sdelvalle57 
Checkpointing takes some time. So just wait for some time.
https://docs.matic.network/docs/develop/ethereum-matic/pos/getting-started

**Comment by ujjwalgupta94** [comment]
We have added `isCheckPointed` method in version 3 of matic.js. Please check at - https://maticnetwork.github.io/matic.js/docs/pos/is-check-pointed/
