### ISSUE TITLE
Unable to resolve module 'tty' from 'node_modules/@maticnetwork/maticjs/dist/matic.node.js'

### ISSUE THREAD

**Issue by liangwu** [maticnetwork/matic.js#224]

**Comment by liangwu** [comment]
does anybody meet this problem?

**Comment by ujjwalgupta94** [comment]
@liangwu which version you are using ?

**Comment by liangwu** [comment]
the latest: 2.0.43

**Comment by liangwu** [comment]
i am using it on my react native project

**Comment by ujjwalgupta94** [comment]
i am using it in vue project but didn't get any error. I also tested in nodejs project, but didn't :(. 

I have created a test project - https://github.com/ujjwalgupta94/maticjs-test, see if you can reproduce here.

**Comment by liangwu** [comment]
I fixed it.

https://github.com/maticnetwork/matic.js/discussions/229

**Comment by ujjwalgupta94** [comment]
That's great @liangwu , thanks for posting the solution.
