### ISSUE TITLE
Is there a method to fetch historical event logs like web3.eth.getPastLogs()?

### ISSUE THREAD

**Issue by zhouhanseng** [maticnetwork/matic.js#226]
Hi, Currently historical contract transaction records can be fetched by [thegraph.com](thegraph.com). Since the service of thegraph is not stable enough, I want to ask is there a method that provided by polygon directly to fetch the historical event logs like `web3.eth.getPastLogs()` does?

**Comment by fuzious** [comment]
Hi @zhouhanseng ,
We have not implemented that functionality, as of now, but meanwhile you can use web3 library for the same.

**Comment by zhouhanseng** [comment]
Thanks @fuzious ,

> The web3-eth package allows you to interact with an Ethereum blockchain and Ethereum smart contracts.

According to [web3 document](https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html), `web3.eth.getPastLogs()` should only work on Ethereum network. Does it work on Polygon network?

**Comment by fuzious** [comment]
Yeah @zhouhanseng  absolutely, you can work with the polygon network completely using web3js be it deploying smart contracts directly to polygon or in your case fetching logs. Matic.JS is more suitable for tasks of cross bridge interactions like depositing to ethereum and withdrawing to matic etc.

**Comment by zhouhanseng** [comment]
Thanks a lot!
