### ISSUE TITLE
Error on React-Native project

### ISSUE THREAD

**Issue by kaje94** [maticnetwork/matic.js#227]
**Describe the bug**
Getting the following error when installing and importing `@maticnetwork/maticjs` into a *React-Native* project.  

Following is a screenshot of the error
![Screenshot_20210627_135643](https://user-images.githubusercontent.com/20398722/123537980-023f7200-d750-11eb-8008-c928e485e015.png)

2.0.43 is the `@maticnetwork/maticjs` version that I'm using

**Comment by ujjwalgupta94** [comment]
@kaje94 one user had the similar problem with react native project. He has posted this solution, please check this - https://github.com/maticnetwork/matic.js/discussions/229

**Comment by kaje94** [comment]
This actually helped to fix this particular error.
Thanks
