### ISSUE TITLE
Lost my UST bridging from polygon to Eth

### ISSUE THREAD

**Issue by MapxanMagar** [maticnetwork/matic.js#243]
Its been 4 days since the bridge , it says success but i cant see balance on neither polygon nor eth wallet.

transction id:0xcef19e689d2aaf70bd7f5e8b92b5058795d620fa71aecee8df96599ddb817c15

**Comment by ujjwalgupta94** [comment]
@MapxanMagar please raise a request on https://support.polygon.technology/support/home
