### ISSUE TITLE
Invalid JSON RPC response

### ISSUE THREAD

**Issue by chahakshah111** [maticnetwork/matic.js#245]
I already have my smart contract deployed on rinkeby network after then I configured it for matic network as per the docs like this: 

matic: {
      provider: function () {
        return new HDWalletProvider(MNEMONIC, `https://rpc-mumbai.matic.today`);
      },
      network_id: 80001,
      confirmations: 2,
      timeoutBlocks: 200,
      skipDryRun: true,
    },

after that when I deploy it using command truffle migrate --network matic it shows me this error: 

Error: Invalid JSON RPC response: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
   
Truffle v5.1.30 (core: 5.1.30)
Node v12.18.4

**Comment by ujjwalgupta94** [comment]
@chahakshah111 could you share what doc link you are following ?

**Comment by ujjwalgupta94** [comment]
this might be issue with RPC, you can switch to some other RPC and check. Here is RPC doc link for reference - https://docs.matic.network/docs/develop/network-details/network/

Let me know if need any other help.
