### ISSUE TITLE
Ability to generate exit proof without sending a transaction

### ISSUE THREAD

**Issue by bogdan** [maticnetwork/matic.js#251]
## Summary

We want these `ExitManager` methods to be exposed in the API:

* `buildPayloadForExit`
* `buildPayloadForExitHermoine`

### Basic example

``` typescript
const payload = matic.buildPayloadForExit(txHash);
const txObject = rootChainManager.methods.exit(payload)
web3.eth.estimateGas({ 
  data: txObject.encodeABI(), 
  to: posRootChainManager.options.address, 
  ...options 
});
```

### Motivation

Current functionality doesn't allow for a more precise control on when and how exit transaction is being sent to blockchain.
The only option is to send the exit transaction and hope for the best.
If you would want to control how transaction is being sent to blockchain, estimate gas usage, raise gas price, cancel transaction, you would want to form and send transaction manually, while matic.js can only generate the `exit(...)` argument aka heavy lifting.

**Comment by ujjwalguptaofficial** [comment]
Right now, you can do like this - 

## buildPayloadForExit

```
import { MaticPOSClient } from "@maticnetwork/maticjs";const client = new MaticPOSClient();
client['posRootChainManager'].exitManager.buildPayloadForExit(txHash, logSignature)
```
### logSignature value

```
const ERC20_TRANSFER_EVENT_SIG = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
const ERC721_TRANSFER_EVENT_SIG = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
const ERC721_WITHDRAW_BATCH_EVENT_SIG = '0xf871896b17e9cb7a64941c62c188a4f5c621b86800e3d15452ece01ce56073df'
const ERC1155_TRANSFER_SINGLE_EVENT_SIG = '0xc3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62'
const ERC1155_TRANSFER_BATCH_EVENT_SIG = '0x4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e595d983b8c0526c8f7fb'
const MESSAGE_SENT_EVENT_SIG = '0x8c5261668696ce22758910d05bab8f186d6eb247ceac2af2e82c7dc17669b036'
const TRANSFER_WITH_METADATA_EVENT_SIG = '0xf94915c6d1fd521cee85359239227480c7e8776d7caf1fc3bacad5c269b66a14'
```

## call exit method

```
const txObject = client['posRootChainManager'].posRootChainManager.methods.exit(payload)
```
now you can use web3 to send the transaction by yourself.

I agree - its not clean code and not documented. But we are working on v3 of maticjs which will have more clean api. Can be tracked here - https://github.com/maticnetwork/matic.js/pull/252/files

**Comment by bogdan** [comment]
Good to know thanks.

**Comment by cristovaoth** [comment]
I built and deployed custom ChildTunnel and RootTunnel on Goerli/Mumbai.

I had already figured that I needed to execute ExitManager.buildPayloadForExitHermione to produce proof, when I stumbled up this issue. Still getting 403. Any tips on how to debug?

(Here's how I'm instantiating the client:)

```
const client = new MaticPOSClient({
    network: 'testnet', // optional, default is testnet
    version: 'mumbai', // optional, default is mumbai
    parentProvider: new HDWalletProvider(config.user.privateKey, 'https://goerli.infura.io/ws/v3/5687b932e....'),
    maticProvider: new HDWalletProvider(config.user.privateKey, 'https://rpc-mumbai.matic.today'),
    posRootChainManager: '0x2890ba17efe978480615e330ecb65333b880928e',
    parentDefaultOptions: { from: config.user.address }, 
    maticDefaultOptions: { from: config.user.address }, 
})
```

**Comment by ujjwalgupta94** [comment]
We have exposed the `ExitUtil` in v3 which can be used to create the proof independently. Have a look at docs - https://maticnetwork.github.io/matic.js/docs/advanced/exit-util/
