### ISSUE TITLE
Invalid JSON RPC response when generating proof for Matic to Ethereum state transfer

### ISSUE THREAD

**Issue by nkrishang** [maticnetwork/matic.js#253]
## Context

I have a [state transfer bridge](https://docs.matic.network/docs/develop/l1-l2-communication/state-transfer) deployed on Goerli and Mumbai. The bridge works - a message passed from Goerli (root tunnel) appears in Mumbai (child tunnel).

I'm trying to generate a proof using [this script](https://docs.matic.network/docs/develop/l1-l2-communication/state-transfer#state-transfer-from-matic-to-ethereum) in the docs :
 
```
// npm i @maticnetwork/maticjs
const maticPOSClient = new require("@maticnetwork/maticjs").MaticPOSClient({
  maticProvider: "https://rpc-mumbai.matic.today", // replace if using mainnet
  parentProvider: "https://rpc.slock.it/goerli", // replace if using mainnet
});
const proof = maticPOSClient.posRootChainManager
  .customPayload(
    "0x3cc9f7e675bb4f6af87ee99947bf24c38cbffa0b933d8c981644a2f2b550e66a", // replace with txn hash of sendMessageToRoot
    "0x8c5261668696ce22758910d05bab8f186d6eb247ceac2af2e82c7dc17669b036" // SEND_MESSAGE_EVENT_SIG, do not change
  )
  .then(console.log);
```

## Issue

Running the script (with all the right parameters/values) returns the following error : `Error: Invalid JSON RPC response: ""`

## Expected

Expected the script to return the bytes proof to call `receiveMessage` with on the root tunnel on Goerli, [as instructed in the docs](https://docs.matic.network/docs/develop/l1-l2-communication/state-transfer#state-transfer-from-matic-to-ethereum).

## Steps to reproduce

Run the above script with the transaction hash 0x9167cb12038d5ae1c6184f658eb67798961b9d360644740c321662feedd08a99.

This is the hash of a transaction that sends a message from the child tunnel on Mumbai, to the root tunnel on Goerli. You can verify this by looking at the `MessageSent` event in the transaction logs [0x9167cb12038d5ae1c6184f658eb67798961b9d360644740c321662feedd08a99](https://mumbai.polygonscan.com/tx/0x9167cb12038d5ae1c6184f658eb67798961b9d360644740c321662feedd08a99)

Here are the verified state bridge contracts:
- `FxChildTunnel` on Mumbai : [0xBa2b61ca39dd6a5D7a135d4B5D3aadDec2B472da](https://mumbai.polygonscan.com/address/0xBa2b61ca39dd6a5D7a135d4B5D3aadDec2B472da)

- `FxRootTunnel` on Goerli: [0xC89498663Ff36F3c3Ed735979dF5574471819263](https://goerli.etherscan.io/address/0xC89498663Ff36F3c3Ed735979dF5574471819263)

The repository I'm working with can be found [here](https://github.com/nkrishang/cross-chain-vrf/tree/example-tunnels).

**Comment by nkrishang** [comment]
### Update

I'm not facing the above problem any longer. I did not change anything about the script or transaction hash mentioned in the issue's opening comment.

Although this is great news for me, I'd like to know how reliable it is to generate a proof using this library, and why I was facing the `Invalid JSON RPC response: ""` error. Otherwise, it's tough to be comfortable using the library in production.

**Comment by ujjwalgupta94** [comment]
This might be issue with the RPC you are using, you can switch to some other RPC and check. 

> regarding matic.js

The library is  nothing but wrapper over web3 and call contracts. We also use this inside our wallet. 

You are free to report any issue if you think there is and we will look into it :).

**Comment by ujjwalgupta94** [comment]
Here is doc for rpc link - https://docs.matic.network/docs/develop/network-details/network/
