### ISSUE TITLE
Exit Tokens: Log nor found in Receipt

### ISSUE THREAD

**Issue by idirall22** [maticnetwork/matic.js#258]
**Describe the bug**
Actually, I'm trying to transfer tokens from mumbai to goerli, the first step that consists of burning the tokens works but the second one exit fails.
![aaa](https://user-images.githubusercontent.com/26064387/128815798-083a85c7-43e7-4cb1-8073-560866e0f624.PNG)

The script that I use is as follow
https://github.com/Shard-Labs/lido-dao/blob/feature-matic/scripts/bridge/bridge.js

https://mumbai.polygonscan.com/address/0x3E46BEFDA7112d8954b923ea6bd9f07c2e615e10

**Comment by ujjwalguptaofficial** [comment]
You are withdrawing matic token right ?

**Comment by idirall22** [comment]
Yes

**Comment by ujjwalguptaofficial** [comment]
matic is a plasma token but you are trying to exit using POS bridge. You will have to use plasma bridge for this - please see this doc - https://docs.matic.network/docs/develop/ethereum-matic/plasma/erc20/#withdraw

**Comment by idirall22** [comment]
@ujjwalguptaofficial Thank you for your help

I followed the link above that you sent me, and I was able to:
1- burn Matic  (success)
2- confirm withdraw (success)
3- exit process (fail)

I'm using the following code to exit, and I using the address of the ERC721 token

```
const exitWithdraw = async () => {
  const matic = await getMaticPlasmaClient()
  const from = config.user1.address
  const res = await matic.processExits('0x2923C8dD6Cdf6b2507ef91de74F1d5E0F11Eac53', {
    from
  })
  console.log(res)
}
```
https://goerli.etherscan.io/address/0x3E46BEFDA7112d8954b923ea6bd9f07c2e615e10

But I get the following error:

![ttt](https://user-images.githubusercontent.com/26064387/128928658-543d45c9-f05d-4ec3-a688-272fbe4553d9.PNG)

**Comment by ujjwalguptaofficial** [comment]
For plasma tokens - Once the checkpoint is submitted, user needs to wait for a challenge period of 7 days long.  

For POS tokens - it is faster around an hour.

**Comment by idirall22** [comment]
even for mumbai -> Goerli testnet ?

**Comment by ujjwalguptaofficial** [comment]
@idirall22 you are calling exit with contract address of withdraw manager proxy `0x2923C8dD6Cdf6b2507ef91de74F1d5E0F11Eac53`, you need to call it with token address.

also Mumbai-> Goerli testnet challenge period is 0 sec.

**Comment by idirall22** [comment]
Hello @ujjwalguptaofficial you already helped me a lot :)
But actually, I'm facing another issue related to  `{ code: -32000, message: 'execution reverted' }`
This error happens after the step burns the tokens.
1- burn Matic (success)
2- confirm withdraw (`{ code: -32000, message: 'execution reverted' }`)
then after setting the gas to '70000' I got the following error:

![azeaeaze](https://user-images.githubusercontent.com/26064387/129531878-283503b9-e807-49aa-83b4-d13ef7a34e7c.PNG)
as you can see the actual **To** address is not correct it should be  `ERC20Predicate = '0x033a0a06dc6e78a518003c81b64f9ca80a55cb06'`
how I can tell to the script to use the right contract?

Thank you again for your help

**Comment by ujjwalguptaofficial** [comment]
Hi @idirall22 

Could you try again please ? I am getting right address. 

> Regarding specifying address manually - 

It's not supported right now, but will add this. Right now i am working on [v3](https://github.com/maticnetwork/matic.js/pull/252), so will add this in v3.
