### ISSUE TITLE
Withdraw Fails to Complete

### ISSUE THREAD

**Issue by JimLynchCodes** [maticnetwork/matic.js#259]
I am seeing a similar issue to this but in decentraland: https://github.com/maticnetwork/matic.js/issues/211

Since I am using a formatic account, I believe there is no way to use the official matic wallet. (please consider supporting this... I just made this wallet for decentraland and was not aware it is unsupported for Polygon network)

![Screen Shot 2021-08-15 at 9 38 42 AM](https://user-images.githubusercontent.com/5354163/129483671-05d6cd02-cb62-4efd-b796-453938a571c2.png)

I did the first step to withdraw, but then whenever I click the "Complete Withdrawal" button nothing happens...

In the console I can see redux thing being logged... "Failure] Finish Withdrawal"

![Screen Shot 2021-08-15 at 11 29 10 AM](https://user-images.githubusercontent.com/5354163/129483715-017da0f6-e821-4c38-a0f3-7250543ea905.png)

What should I do? How do I access my mana and get it to the ethereum network? wtf even happened? how long to I need to wait? Will it revert back to the polygon network if I do nothing? when will that happen?

^ all these things should be displayed to the user. Without them it's very confusing and worrying UX...

**Comment by ujjwalguptaofficial** [comment]
seems like its an issue from decentraland. looking at logs - you can see the error in payload - 

```
n.provider.on is not a function
```

You can complete your withdrawal process by following ways - 

1. Use this app - https://polygon-withdraw.matic.network/ . Paste your burn transaction hash and finish your tx.
2. You can also use matic.js to finish your tx. Take a look at this erc20 pos withdrawal exit - https://github.com/maticnetwork/matic.js/blob/master/examples/pos/erc20/exit.js


I hope this helps

**Comment by rebmemer** [comment]
Hi, I don't think this is actually resolved.  The first link you sent doesn't support fortmatic wallets and the second link is dead so can't be used - meaning there is no solution?

**Comment by ujjwalgupta94** [comment]
Hi

The file is changed, so the url. Please have a look at - https://github.com/maticnetwork/matic.js/blob/master/examples/pos/erc20/withdraw_exit.js
