### ISSUE TITLE
Provider not set or invalid

### ISSUE THREAD

**Issue by jarcodallo** [maticnetwork/matic.js#264]
**Describe the bug**

Currently I'm trying to instance a Maticjs client, but I got `Provider not set or invalid`. According to [SDKClient](https://github.com/maticnetwork/matic.js/blob/master/src/common/SDKClient.ts#L16), if you pass `parentProvider` on null or undefined, the `Web3Client` should use `options.network.Main.RPC`. The problem is that `RPC` is not define in [network/mainnet/v1/index.json](https://github.com/maticnetwork/static/blob/master/network/mainnet/v1/index.json#L2)

#### Hint

The expecting behavior should be a Maticjs instance with the default RPC provider.

```ts
const MaticPlasmaClient = require("@maticnetwork/maticjs").default;
const maticPlasmaClient = new MaticPlasmaClient({
  network: 'mainnet',
  version: 'v1',
  maticProvider: undefined,
  parentProvider: undefined,
  parentDefaultOptions: {},
  maticDefaultOptions: {}
});
maticPlasmaClient.initialize().then(() => console.log('success')).catch((err) => console.error(err))
```

![image](https://user-images.githubusercontent.com/3802516/131039280-0e64b844-2fee-46f2-94a9-f7f7c0965ad3.png)

**Comment by ujjwalguptaofficial** [comment]
that is because RPC value for main network is not present in static repo - https://github.com/maticnetwork/static/blob/master/network/mainnet/v1/index.json

Anyway we are not saying anywhere regarding default RPC, so its mandatory to specify the provider.

We will remove this code in v3 of maticjs.
