### ISSUE TITLE
Exit of burn proof gives "Unexpected Token < at JSON"

### ISSUE THREAD

**Issue by ZackMcClary34** [maticnetwork/matic.js#270]
**Describe the bug**
I am trying to "exit" with the transaction https://mumbai.polygonscan.com/tx/0xa7d25c9223eb8fd8145ea54ec518f7aaef1954f291bb88d7efbab34897b9987a . But when I do I get "Unexpected token < at JSON at position 0". I can also verify the block has past checkpoint here... https://apis.matic.network/api/v1/mumbai/block-included/18921480

#### Hint

* Shouldn't I be able to see the exit work successfully?
<img width="870" alt="Screen Shot 2021-09-14 at 10 20 02 AM" src="https://user-images.githubusercontent.com/17221806/133286010-6b1b025b-f567-4ac6-88ec-fab357984505.png">

**Comment by ZackMcClary34** [comment]
Also want to add the response details 
<img width="1426" alt="Screen Shot 2021-09-14 at 2 32 33 PM" src="https://user-images.githubusercontent.com/17221806/133322112-029ad167-18fd-487b-a3a5-af58f64d72ff.png">

**Comment by ujjwalguptaofficial** [comment]
is the issue still persist ?

**Comment by ZackMcClary34** [comment]
Yes @ujjwalguptaofficial

**Comment by ujjwalguptaofficial** [comment]
@ZackMcClary34 what version of matic.js you are using ?
