### ISSUE TITLE
Explicitly fetch `withdrawManager` and `depositManager` address from rootChain contract if not provided

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/matic.js#31]

**Comment by atvanguard** [comment]
Under the new design, we would need to fetch `registry` address from `rootChain` and then `registry.getDepositManagerAddress()` and `registry.getWithdrawManagerAddress()`

**Comment by atvanguard** [comment]
Will provide this options under a flag, user can have the contract address automatically pulled from registry to decide to give it manually as well.

**Comment by rahuldamodar94** [comment]
Already done.
