### ISSUE TITLE
Dependency vulnerability

### ISSUE THREAD

**Issue by andrewkmin** [maticnetwork/matic.js#332]
Apologies if this is the wrong avenue for reporting, but just wanted to highlight a vulnerability in a dependency of this project:

**Describe the bug**
`ethereumjs-block` has been deprecated: https://github.com/ethereumjs/ethereumjs-block
It can now be found via `@ethereumjs/block`. 
`ethereumjs-block` references the package `merkle-patricia-tree v2.3.2`, which references `async v1.5.2`, which has a high-risk vulnerability: See: https://snyk.io/test/npm/merkle-patricia-tree/2.3.2 / https://snyk.io/test/npm/async/1.5.2

#### Hint
Would like to request that a more recent version of `ethereumjs-block` is used; however, given this will probably require the usage of `@ethereumjs/block`, there may be some additional client code changes required.

**Comment by ujjwalgupta94** [comment]
ok, will do these changes.

**Comment by lorines** [comment]
Hi @ujjwalgupta94 do you have any updates on this? Could we have the fix by tomorrow?

**Comment by ujjwalgupta94** [comment]
@lorines we are working on the version update, but seems like it will take some time. The API's are changed and so need to figure out changes. 

I am working on the PR here - https://github.com/maticnetwork/matic.js/pull/333 , feel free to contribute.

Also BTW - the vulnerability is nothing related to security, its prototype pollution. So nothing to be taken in a serious manner, but i will try to fix ASAP.

**Comment by lorines** [comment]
@ujjwalgupta94 it does seem link a security risk: https://portswigger.net/daily-swig/prototype-pollution-the-dangerous-and-underrated-vulnerability-impacting-javascript-applications

**Comment by ujjwalgupta94** [comment]
this has been fixed in v - 3.3.0
