### ISSUE TITLE
importing `matic.js` throws an exception in react-native

### ISSUE THREAD

**Issue by rawatnaresh** [maticnetwork/matic.js#336]
**Describe the bug**
 
```Error: Unable to resolve module events from /matic/node_modules/@ethereumjs/common/dist.browser/index.js: events could not be found within the project or in these directories```
#### Hint

- created a new react-native project using `npx react-native init MyApp`
- installed 
  - `@maticnetwork/maticjs`
  -  `@maticnetwork/maticjs-ethers`
  -  `@maticnetwork/maticjs-web3`

- imported and use web3 plugin
```js
import {use} from '@maticnetwork/maticjs';
import {Web3ClientPlugin} from '@maticnetwork/maticjs-web3';

// install web3 plugin
use(Web3ClientPlugin);

```
- Starting the app throws an exception

![Screen Shot 2022-05-06 at 17 00 15](https://user-images.githubusercontent.com/29520305/167121506-35b12f49-d394-404e-b5e6-88b0bbb68dbf.png)

- Hers's the reproducible source code. https://github.com/rawatnaresh/matic-test/blob/main/index.js

**Comment by ujjwalgupta94** [comment]
ok, will have a look today.
