### ISSUE TITLE
Typo in `src/pos/exit_util.ts`: "grater" should be "greater"

### ISSUE THREAD

**Issue by flanagansteve** [maticnetwork/matic.js#415]
In [the error message](https://github.com/maticnetwork/matic.js/blob/481d51af6627bf6fa0ec505974c9d57a5ba2ad4c/src/pos/exit_util.ts#L300) for an out-of-range token index, the message says the index is "grater" than the number of tokens in this transaction, but it should be "greater"

I tried to open a PR for this, but got a 403 from https://github.com/maticnetwork/matic.js.git/ when trying to push to my feature branch.

```
remote: Permission to maticnetwork/matic.js.git denied to flanagansteve.
fatal: unable to access 'https://github.com/maticnetwork/matic.js.git/': The requested URL returned error: 403
```

**Comment by nitinmittal23** [comment]
Thank you for bringing this to our attention. We'll address it in the upcoming version
