### ISSUE TITLE
https://static.matic.network/ URLs are breaking

### ISSUE THREAD

**Issue by mudgen** [maticnetwork/matic.js#416]
An older version of matic.js is being used that is failing because it is using "https://static.matic.network/" URLs which are not working anymore.  Is this fixed in the latest version of matic.js?

Specifically we are getting these Javascript errors in Chrome on a laptop:

> specific javascript error is "net::ERR_NAME_NOT_RESOLVED"    
> Error: network mainnet - v1 is not supported

The error is specifically occurring when the user clicks on a "Claim" button to withdraw ERC20 tokens (aUSDC) on Ethereum that were bridged from Polygon.

I attached a screenshot of the javascript error.

![aavegotchierroronclaim](https://github.com/maticnetwork/matic.js/assets/49092/67c24835-1a5d-4436-b424-8ce463c24e64)

**Comment by nitinmittal23** [comment]
@mudgen Please use the latest version of Matic.js as static URLS are changed to https://static.polygon.technology/
