### ISSUE TITLE
Provide a exactly value type on network & version

### ISSUE THREAD

**Issue by HuberTRoy** [maticnetwork/matic.js#426]
## Summary

https://github.com/maticnetwork/matic.js/blob/master/src/interfaces/base_client_config.ts#L1

In this type definition, use an exactly value would be better for use.

For someone who don't know what network & version is.

```
export interface IBaseClientConfig {
    network: "testnet" | "mainnet";
    version: "mumbai" | "v1";
    parent?: {
        provider: any;
        defaultConfig: {
            from: string;
        }
    };
    child?: {
        provider: any;
        defaultConfig: {
            from: string;
        }
    };
    log?: boolean;
    requestConcurrency?: number;

}
```

**Comment by nitinmittal23** [comment]
All the networks and versions can be found here https://github.com/maticnetwork/static/tree/master/network
