### ISSUE TITLE
Example file get-matic-token-address.js doesnt run without a code change

### ISSUE THREAD

**Issue by jamesmorgan** [maticnetwork/matic.js#45]
bad import within the `examples` project

`const Matic = require('../../lib/index').default`

should be 

`const Matic = require('maticjs').default`

file: 

https://github.com/maticnetwork/matic.js/blob/master/examples/node/get-matic-token-address.js

**Comment by shahbhavir** [comment]
https://github.com/maticnetwork/matic.js/pull/47 solves this.
Thank you @jamesmorgan for reporting 👏 
Any more suggestions/issues, please feel free to report 👍
