### ISSUE TITLE
example/node deposit code failing to execute

### ISSUE THREAD

**Issue by nolim1t** [maticnetwork/matic.js#84]
Need documentation in config.js for PARENT_TEST_TOKEN

Seems to be a required option for deposit

**Comment by nglglhtr** [comment]
The token you'd like to deposit, if not already, must be mapped on Matic
otherwise you can use TEST erc20 tokens, with addresses:
`0x28C8713DDe7F063Fdc4cA01aB2A8856e0F243Fec` on Ropsten 
and `0x9a93c912F4eFf0254d178a18ACD980C1B05b57b0` on Matic testnet v3

**Comment by nolim1t** [comment]
what I was supposed to say as in ```deposit-ERC20.js```  the  example code which I'm using to learn the platform does not even run.

## Steps

1. Update ```FROM_ADDRESS``` and ```PRIVATE_KEY``` with ropsten private key
2. do a ```npm install``` and pull down all the dependencies
3. Run ```node deposit-ERC20.js```

### Actual Result

Fails to run because ```PARENT_TEST_TOKEN``` is missing from the example config.js

### Expected result

Working config.js

**Comment by nolim1t** [comment]
see https://github.com/maticnetwork/matic.js/blob/58f069cc01a1366e3e5d093d6b355158a09a4911/examples/node/deposit-ERC20.js#L7

This config option does not exist

**Comment by nolim1t** [comment]
I'm using my own deployed contracts which have ropsten and matic network equivalents so I can control issuance.

However the example code for deposit seems to fail with a transaction Reverted from the deposit manager contract (0x3bc6701ca1c32bbac8d1ffa2294ee3444ad93989).

 Is the any way of catching any exceptions to gather more information on why?

**Comment by nglglhtr** [comment]
> I'm using my own deployed contracts which have ropsten and matic network equivalents so I can control issuance actually have some tokens under my own account.

For deposits to work, the token is supposed to be mapped on root and child plasma contracts. (This: https://github.com/maticnetwork/contracts/blob/a4c26d59ca6e842af2b8d2265be1da15189e29a4/contracts/root/depositManager/DepositManager.sol#L158 is the reason for revert) 

The best way for which would be for you to share your token address and we'll map it for you.
The mapping process deploys a new child token on Matic chain.

**Comment by nolim1t** [comment]
> > I'm using my own deployed contracts which have ropsten and matic network equivalents so I can control issuance actually have some tokens under my own account.
> 
> For deposits to work, the token is supposed to be mapped on root and child plasma contracts. (This: https://github.com/maticnetwork/contracts/blob/a4c26d59ca6e842af2b8d2265be1da15189e29a4/contracts/root/depositManager/DepositManager.sol#L158 is the reason for revert)
> 
> The best way for which would be for you to share your token address and we'll map it for you.
> The mapping process deploys a new child token on Matic chain.

On Matic
0x34D13f8DFb4e31ba10B62C064A891EE3bb338396

On Ropsten
0x2Ca2C207a4Cd1796276Cf380D02E9a9Cc951bb28

**Comment by nolim1t** [comment]
It's established that the example code is using the old API

**Comment by Araton95** [comment]
@nolim1t the same case for me.

Is there a way to map token myself?

If not please map this tokens too:

Ropsten 1 = 0x42e4F63353f8A166d0F0E7bE468275a3A0e973C9
Ropsten 2 = 0xB0B5e8E193A303EeC9F64f56eF6EA632F6DE5B1d

Matic 1 = 0x101188dd6e3eeb0a3efb35722fda2c29f17aaed1
Matic 2 = 0x0a61617e61cdf8cd1bad0d3edfe6e7cb586fe0de

**Comment by nglglhtr** [comment]
@Araton95 the mapping is done by an owner account. So i will map it for you

Also, the mapping process is such that a new child token is deployed on Matic , so ideally you don't need to deploy there. 
only root token address is required 

Here are the mapped addresses on matic you can use: 

Matic 1 (root: Ropsten 1) : 0xa2e5d90FB4306B313d1B43910DF415D125a02Bd3
Matic 2 (root: Ropsten 2) : 0xc06C9E3c1407d115A13e4746c605f68BECE5C2D2

These are mapped on testnetv3 
config: https://static.matic.network/network/testnet/v3/index.json
example: https://github.com/nglglhtr/maticjs-sdk-sample/blob/master/beta/erc20.js

**Comment by nglglhtr** [comment]
If you have any further queries please ask on our technical support group https://t.me/joinchat/It3Y81DKW0p9gu1ztFgAUg

**Comment by Araton95** [comment]
@nglglhtr great, thanks
